apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"limits":{"ephemeral-storage":"1Gi","memory":"350Mi"},"requests":{"cpu":"1m","ephemeral-storage":"1Gi","memory":"5Mi"},"name":"operator"},{"limits":{"ephemeral-storage":"1Gi","memory":"125Mi"},"requests":{"cpu":"1m","ephemeral-storage":"1Gi","memory":"5Mi"},"name":"bitbox"}]},"output":{"containers":[{"limits":{"ephemeral-storage":"1Gi","memory":"350Mi"},"requests":{"cpu":"49m","ephemeral-storage":"1Gi","memory":"47Mi"},"name":"operator"},{"limits":{"ephemeral-storage":"1Gi","memory":"125Mi"},"requests":{"cpu":"1m","ephemeral-storage":"1Gi","memory":"5Mi"},"name":"bitbox"}]},"computeClassAtAdmission":"Default","modified":true}'
    autopilot.gke.io/warden-version: 33.33.21-gke.1
    deployment.kubernetes.io/revision: '5'
    meta.helm.sh/release-name: sweet-operator
    meta.helm.sh/release-namespace: sweet
  creationTimestamp: '2026-01-08T23:49:34Z'
  generation: 6
  labels:
    app.kubernetes.io/instance: sweet
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sweet-operator
  name: sweet-operator
  namespace: sweet
  resourceVersion: '1768199058187375015'
  uid: 17db078b-c37f-4ceb-a6bd-71a9a8ccce85
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: sweet
      app.kubernetes.io/name: sweet-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        app.kubernetes.io/component: operator
        app.kubernetes.io/name: operator
        app.kubernetes.io/part-of: sweet
        checksum/config: f08860bbbe3640d356a3b45449c7a97120f9c0b37359d79bde8c9ed727524cb9
        checksum/secret: c2435bcf68695eb954ecfd27b34802cf710da1976ac26980a77c50e0e16ba0b2
        kubectl.kubernetes.io/restartedAt: '2026-01-09T15:56:14-08:00'
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sweet
        app.kubernetes.io/name: sweet-operator
    spec:
      containers:
      - args:
        - --skipScanner=false
        - --label=stack:default
        - --frontierExtraValues=,priorityClass.enabled=true,priorityClass.value=1000,sensor.enabled=false,sensor.hostNetwork=false,sensor.hostPID=false,serviceAccount.create=true
        - --operatorExtraValues=,image.pullPolicy=IfNotPresent,image.repository=registry.sweet.security,proxy.enabled=false,proxy.port=1080,proxy.protocol=socks5h,operator.bitbox.resources.limits.memory=125Mi,operator.bitbox.resources.requests.cpu=1m,operator.bitbox.resources.requests.memory=5Mi,operator.labels.stack=default,operator.resources.limits.memory=350Mi,operator.resources.requests.cpu=1m,operator.resources.requests.memory=5Mi,priorityClass.enabled=false,priorityClass.value=1000,frontier.extraValues.priorityClass.enabled=true,frontier.extraValues.priorityClass.value=1000,frontier.extraValues.sensor.enabled=false,frontier.extraValues.sensor.hostNetwork=false,frontier.extraValues.sensor.hostPID=false,frontier.extraValues.serviceAccount.create=true
        - --scannerExtraValues=
        command:
        - /sweet/operator
        env:
        - name: RUST_LOG
          value: info
        - name: STDOUT_RUST_LOG
          value: 'off'
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SWEET_RELEASE_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: sweet-operator
        - secretRef:
            name: sweet-operator
        image: registry.sweet.security/operator:af88a2f6bc4664a8fd68b4a8f420b7b4f8e25362
        imagePullPolicy: IfNotPresent
        name: operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            ephemeral-storage: 1Gi
            memory: 350Mi
          requests:
            cpu: 49m
            ephemeral-storage: 1Gi
            memory: 47Mi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/sweet
          name: sweet-logs
      - args:
        - --log-path=/var/log/sweet
        - --log-destination-url=https://logger.sweet.security
        - --metric-source-url=http://127.0.0.1:8080/metrics
        - --metric-destination-url=https://vincent.sweet.security/v1/scrape
        - --collect-self-metrics-interval=1min
        - --collect-url-metrics-interval=1min
        - --log-read-interval=15s
        - --poster-gzip
        command:
        - /sweet/bitbox
        env:
        - name: RUST_LOG
          value: info
        - name: STDOUT_RUST_LOG
          value: 'off'
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SWEET_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: SWEET_CLUSTER_ID
              name: sweet-operator
        envFrom:
        - secretRef:
            name: sweet-operator
        image: registry.sweet.security/bitbox:f5783c545dd3192b9fdfe0c77708d25cae4d632f
        imagePullPolicy: IfNotPresent
        name: bitbox
        resources:
          limits:
            ephemeral-storage: 1Gi
            memory: 125Mi
          requests:
            cpu: 1m
            ephemeral-storage: 1Gi
            memory: 5Mi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/sweet
          name: sweet-logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: sweet-operator
      serviceAccountName: sweet-operator
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
      volumes:
      - emptyDir: {}
        name: sweet-logs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: '2026-01-08T23:49:34Z'
    lastUpdateTime: '2026-01-10T00:01:25Z'
    message: ReplicaSet "sweet-operator-76d6b6bc5d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: 'True'
    type: Progressing
  - lastTransitionTime: '2026-01-12T06:24:18Z'
    lastUpdateTime: '2026-01-12T06:24:18Z'
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: 'True'
    type: Available
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
