apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"limits":{"ephemeral-storage":"1Gi","memory":"1Gi"},"requests":{"cpu":"5m","ephemeral-storage":"1Gi","memory":"512Mi"},"name":"scanner"},{"limits":{"ephemeral-storage":"1Gi","memory":"75Mi"},"requests":{"cpu":"5m","ephemeral-storage":"1Gi","memory":"50Mi"},"name":"bitbox"}]},"output":{"containers":[{"limits":{"ephemeral-storage":"1Gi","memory":"1Gi"},"requests":{"cpu":"80m","ephemeral-storage":"1Gi","memory":"512Mi"},"name":"scanner"},{"limits":{"ephemeral-storage":"1Gi","memory":"75Mi"},"requests":{"cpu":"5m","ephemeral-storage":"1Gi","memory":"50Mi"},"name":"bitbox"}]},"computeClassAtAdmission":"Default","modified":true}'
    autopilot.gke.io/warden-version: 33.33.21-gke.1
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: sweet-scanner
    meta.helm.sh/release-namespace: sweet
  creationTimestamp: '2026-01-08T23:50:45Z'
  generation: 1
  labels:
    app.kubernetes.io/instance: sweet-scanner
    app.kubernetes.io/name: sweet-scanner
    pod-template-hash: 84dbc87d5d
  name: sweet-scanner-84dbc87d5d
  namespace: sweet
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: sweet-scanner
    uid: 403cebad-9442-46ff-b746-ebd92b328245
  resourceVersion: '1768199120209535008'
  uid: effb7c1e-667b-41a4-bf72-9444904e50ed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: sweet-scanner
      app.kubernetes.io/name: sweet-scanner
      pod-template-hash: 84dbc87d5d
  template:
    metadata:
      annotations:
        app.kubernetes.io/component: scanner
        app.kubernetes.io/name: scanner
        app.kubernetes.io/part-of: sweet
        checksum/config: a66b8af8eef3bc042484f35a2ad43bb53a128f5cbef61a140041db4bce703d42
        checksum/secret: 150cbb2f3bb464f63889ab05d69f1f5b9dbdb240882724180755c717cf0e4dc0
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sweet-scanner
        app.kubernetes.io/name: sweet-scanner
        pod-template-hash: 84dbc87d5d
    spec:
      containers:
      - env:
        - name: GOMEMLIMIT
          value: 924MiB
        envFrom:
        - configMapRef:
            name: sweet-scanner
        - secretRef:
            name: sweet-scanner
        image: registry.sweet.security/scanner:a69a6fbc34f9c8d9b5eeebb44dc612a8f242f01f
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: scanner
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            ephemeral-storage: 1Gi
            memory: 1Gi
          requests:
            cpu: 80m
            ephemeral-storage: 1Gi
            memory: 512Mi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/sweet
          name: sweet-logs
      - args:
        - --log-path=/var/log/sweet
        - --log-destination-url=https://logger.sweet.security
        - --metric-source-url=http://127.0.0.1:8080/metrics
        - --metric-destination-url=https://vincent.sweet.security/v1/scrape
        - --collect-self-metrics-interval=1min
        - --collect-url-metrics-interval=1min
        - --log-read-interval=15s
        - --poster-gzip
        command:
        - /sweet/bitbox
        env:
        - name: RUST_LOG
          value: info
        - name: STDOUT_RUST_LOG
          value: '"off"'
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SWEET_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: SWEET_CLUSTER_ID
              name: sweet-scanner
        envFrom:
        - secretRef:
            name: sweet-scanner
        image: registry.sweet.security/bitbox:2fceb477fb90ff3febbed42fe39a9af0ca71caa8
        imagePullPolicy: IfNotPresent
        name: bitbox
        resources:
          limits:
            ephemeral-storage: 1Gi
            memory: 75Mi
          requests:
            cpu: 5m
            ephemeral-storage: 1Gi
            memory: 50Mi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/sweet
          name: sweet-logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: sweet-scanner
      serviceAccountName: sweet-scanner
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
      volumes:
      - emptyDir: {}
        name: sweet-logs
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
